HOME: /t3home/frejalom
USER: frejalom
SLURM_JOB_ID: 320469
HOSTNAME: t3wn61
CMSSW RELEASE BASE  /cvmfs/cms.cern.ch/slc7_amd64_gcc12/cms/cmssw/CMSSW_14_2_0_pre4
%MSG-i AlpakaService:  (NoModuleName) 10-Apr-2025 22:55:14 CEST pre-events
AlpakaServiceSerialSync succesfully initialised.
Found 1 device:
  - Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz
%MSG
10-Apr-2025 22:55:17 CEST  Initiating request to open file root://xrootd-cms.infn.it//store/relval/CMSSW_14_2_0_pre4/RelValTTbar_14TeV/GEN-SIM-RECO/PU_141X_mcRun4_realistic_v3_STD_2026D110_PU-v2/2590000/667ce29f-cefa-45dc-8a6b-350fe5b73bd4.root
%MSG-w XrdAdaptorInternal:  file_open 10-Apr-2025 22:55:19 CEST pre-events
Failed to open file at URL root://cms-xrd-global.cern.ch:1094//store/relval/CMSSW_14_2_0_pre4/RelValTTbar_14TeV/GEN-SIM-RECO/PU_141X_mcRun4_realistic_v3_STD_2026D110_PU-v2/2590000/667ce29f-cefa-45dc-8a6b-350fe5b73bd4.root?tried=+1213llrxrd-redir.in2p3.fr&xrdcl.requuid=1407a764-b0ca-4075-a617-5e65393203b0.
%MSG
%MSG-w XrdAdaptorInternal:  file_open 10-Apr-2025 22:55:19 CEST pre-events
Failed to open file at URL root://cms-xrd-global.cern.ch:1094//store/relval/CMSSW_14_2_0_pre4/RelValTTbar_14TeV/GEN-SIM-RECO/PU_141X_mcRun4_realistic_v3_STD_2026D110_PU-v2/2590000/667ce29f-cefa-45dc-8a6b-350fe5b73bd4.root?tried=+1213llrxrd-redir.in2p3.fr,&xrdcl.requuid=83262f87-0ecf-4cf0-97d7-710dd457e921.
%MSG
----- Begin Fatal Exception 10-Apr-2025 22:55:19 CEST-----------------------
An exception of category 'FileOpenError' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing input source of type PoolSource
   [2] Calling RootInputFileSequence::initTheFile()
   [3] Calling StorageFactory::open()
   [4] Calling XrdFile::open()
Exception Message:
Failed to open the file 'root://xrootd-cms.infn.it//store/relval/CMSSW_14_2_0_pre4/RelValTTbar_14TeV/GEN-SIM-RECO/PU_141X_mcRun4_realistic_v3_STD_2026D110_PU-v2/2590000/667ce29f-cefa-45dc-8a6b-350fe5b73bd4.root'
   Additional Info:
      [a] Input file root://xrootd-cms.infn.it//store/relval/CMSSW_14_2_0_pre4/RelValTTbar_14TeV/GEN-SIM-RECO/PU_141X_mcRun4_realistic_v3_STD_2026D110_PU-v2/2590000/667ce29f-cefa-45dc-8a6b-350fe5b73bd4.root could not be opened.
      [b] XrdCl::File::Open(name='root://xrootd-cms.infn.it//store/relval/CMSSW_14_2_0_pre4/RelValTTbar_14TeV/GEN-SIM-RECO/PU_141X_mcRun4_realistic_v3_STD_2026D110_PU-v2/2590000/667ce29f-cefa-45dc-8a6b-350fe5b73bd4.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.
' (errno=3011, code=400). No additional data servers were found.
      [c] Last URL tried: root://cms-xrd-global.cern.ch:1094//store/relval/CMSSW_14_2_0_pre4/RelValTTbar_14TeV/GEN-SIM-RECO/PU_141X_mcRun4_realistic_v3_STD_2026D110_PU-v2/2590000/667ce29f-cefa-45dc-8a6b-350fe5b73bd4.root?tried=+1213llrxrd-redir.in2p3.fr,&xrdcl.requuid=83262f87-0ecf-4cf0-97d7-710dd457e921
      [d] Problematic data server: cms-xrd-global.cern.ch:1094
      [e] Disabled source: cms-xrd-global.cern.ch:1094
----- End Fatal Exception -------------------------------------------------
logfile
pv_cfg.py
cp: cannot stat 'pv.root': No such file or directory
