HOME: /t3home/frejalom
USER: frejalom
SLURM_JOB_ID: 320350
HOSTNAME: t3wn60
CMSSW RELEASE BASE  /cvmfs/cms.cern.ch/slc7_amd64_gcc12/cms/cmssw/CMSSW_14_2_0_pre4
%MSG-i AlpakaService:  (NoModuleName) 10-Apr-2025 22:49:03 CEST pre-events
AlpakaServiceSerialSync succesfully initialised.
Found 1 device:
  - Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz
%MSG
10-Apr-2025 22:49:08 CEST  Initiating request to open file root://xrootd-cms.infn.it//store/relval/CMSSW_14_2_0_pre4/RelValTTbar_14TeV/GEN-SIM-RECO/PU_141X_mcRun4_realistic_v3_STD_2026D110_PU-v2/2590000/d7d4b8cb-cc39-4095-ab9e-6a6ae59dea7f.root
%MSG-w XrdAdaptorInternal:  file_open 10-Apr-2025 22:50:15 CEST pre-events
Failed to open file at URL root://cms-xrd-global.cern.ch:1094//store/relval/CMSSW_14_2_0_pre4/RelValTTbar_14TeV/GEN-SIM-RECO/PU_141X_mcRun4_realistic_v3_STD_2026D110_PU-v2/2590000/d7d4b8cb-cc39-4095-ab9e-6a6ae59dea7f.root?tried=+1213llrxrd-redir.in2p3.fr&xrdcl.requuid=6449c00a-9b6f-4cf6-af16-9e16b909015e.
%MSG
%MSG-w XrdAdaptorInternal:  file_open 10-Apr-2025 22:50:15 CEST pre-events
Failed to open file at URL root://cms-xrd-global.cern.ch:1094//store/relval/CMSSW_14_2_0_pre4/RelValTTbar_14TeV/GEN-SIM-RECO/PU_141X_mcRun4_realistic_v3_STD_2026D110_PU-v2/2590000/d7d4b8cb-cc39-4095-ab9e-6a6ae59dea7f.root?tried=+1213llrxrd-redir.in2p3.fr,&xrdcl.requuid=095ba837-cda4-4da7-aadd-75bb9539f984.
%MSG
----- Begin Fatal Exception 10-Apr-2025 22:50:15 CEST-----------------------
An exception of category 'FileOpenError' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing input source of type PoolSource
   [2] Calling RootInputFileSequence::initTheFile()
   [3] Calling StorageFactory::open()
   [4] Calling XrdFile::open()
Exception Message:
Failed to open the file 'root://xrootd-cms.infn.it//store/relval/CMSSW_14_2_0_pre4/RelValTTbar_14TeV/GEN-SIM-RECO/PU_141X_mcRun4_realistic_v3_STD_2026D110_PU-v2/2590000/d7d4b8cb-cc39-4095-ab9e-6a6ae59dea7f.root'
   Additional Info:
      [a] Input file root://xrootd-cms.infn.it//store/relval/CMSSW_14_2_0_pre4/RelValTTbar_14TeV/GEN-SIM-RECO/PU_141X_mcRun4_realistic_v3_STD_2026D110_PU-v2/2590000/d7d4b8cb-cc39-4095-ab9e-6a6ae59dea7f.root could not be opened.
      [b] XrdCl::File::Open(name='root://xrootd-cms.infn.it//store/relval/CMSSW_14_2_0_pre4/RelValTTbar_14TeV/GEN-SIM-RECO/PU_141X_mcRun4_realistic_v3_STD_2026D110_PU-v2/2590000/d7d4b8cb-cc39-4095-ab9e-6a6ae59dea7f.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.
' (errno=3011, code=400). No additional data servers were found.
      [c] Last URL tried: root://cms-xrd-global.cern.ch:1094//store/relval/CMSSW_14_2_0_pre4/RelValTTbar_14TeV/GEN-SIM-RECO/PU_141X_mcRun4_realistic_v3_STD_2026D110_PU-v2/2590000/d7d4b8cb-cc39-4095-ab9e-6a6ae59dea7f.root?tried=+1213llrxrd-redir.in2p3.fr,&xrdcl.requuid=095ba837-cda4-4da7-aadd-75bb9539f984
      [d] Problematic data server: cms-xrd-global.cern.ch:1094
      [e] Disabled source: cms-xrd-global.cern.ch:1094
----- End Fatal Exception -------------------------------------------------
logfile
pv_cfg.py
cp: cannot stat 'pv.root': No such file or directory
